---
fixtures:
  symlinks:
    profile: "site-modules/profile"
    role: "site-modules/role"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
    concat:
      repo: "puppetlabs/concat"
    firewall:
      repo: "puppetlabs/firewall"
    ntp:
      repo: "puppetlabs/ntp"
    logrotate:
      repo: "puppet/logrotate"
    systemd:
      repo: "puppet/systemd"
    augeasproviders_core:
      repo: "puppet/augeasproviders_core"
    augeasproviders_sysctl:
      repo: "puppet/augeasproviders_sysctl"
    ufw:
      repo: "kogitoapp/ufw"
    resource_api:
      repo: "puppetlabs/resource_api"
    ssh:
      repo: "saz/ssh"
    vcsrepo:
      repo: "puppetlabs/vcsrepo"
    fail2ban:
      repo: "puppet/fail2ban"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "10.5.0"
    foreman:
      repo: "theforeman/foreman"
      ref: "26.2.1"
    foreman_proxy:
      repo: "theforeman/foreman_proxy"
      ref: "26.0.0"
    puppet:
      repo: "theforeman/puppet"
      ref: "20.1.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "9.4.0"
    extlib:
      repo: "puppet/extlib"
      ref: "7.1.0"
    dns:
      repo: "theforeman/dns"
      ref: "11.0.0"
    inifile:
      repo: "puppetlabs/inifile"
