---
require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'modules/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'Puppetfile'

# Disable some style cops that conflict with Puppet conventions
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 140
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/ImplicitSubject:
  Enabled: false

# Disable Capybara cops (causes RuboCop crashes on rspec-puppet code)
Capybara:
  Enabled: false
