---
require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'modules/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'Puppetfile'

# Disable some style cops that conflict with Puppet conventions
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 140
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/ImplicitSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

# Disable cops that don't apply to Puppet/rspec-puppet testing
# These are loaded by rubocop-rspec but cause crashes or warnings
Capybara:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false

FactoryBot:
  Enabled: false

RSpecRails:
  Enabled: false
